version: "3"


services:
    nginx:
      image:
        "nginx:latest"
      ports:
        - "80:80"
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./:/work
      command: ["/work/dashboard/wait-for-it.sh", "django:38000", "--", "nginx", "-g", "daemon off;"]
