version: "3"


services:
    nginx:
      image:
        "nginx:latest"
      ports:
        - "30080:80"
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./:/work
      command: ["nginx", "-g", "daemon off;"]
